### ISSUE TITLE
Slide Show (S9) v3.0 - Upgrade to Markdown from Textile?

### ISSUE THREAD

**Issue by geraldb** [avillafiorita/slideshow-reveal.js#5]
Hello,
  @avillafiorita  First thanks for the great reveal.js slide show package. FYI: I've updated Slide Show with breaking changes. What's news in v3.0?
- Slide Show templates are now using Liquid (only) - and, thus, work on GitHub Pages "out-of-the-box" for previews, etc.
- Note: In your source all continues to work as expected e.g. all ERB macros work (e.g. <%= Date.today %> or <%= 3+2 %> etc.
- Sorry to break the news - Textile is no longer supported in V3.0 - only Markdown (w/ kramdown). If I can help in the transition / upgrade, please let me know.

Cheers.
PS: You can - of course - continue to use the 2.x series. Please use a Gemfile (or do NOT update).

**Comment by avillafiorita** [comment]
retired: it now points to the slideshow-templates page.
